# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-10 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainwheel',
            table='axf_wheel',
        ),
    ]
