# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200510_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwheel',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
